services:
  web:
    build: .
    expose:
      - "4321"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/prisma/database.db
      - JWT_SECRET=yatjkbazibjgfijgghjafdazfqfouafafhhis
      - SITE_URL=http://localhost:4321
    volumes:
      - ./prisma:/app/prisma

  prisma-studio:
    build: .
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/prisma/prisma/database.db
    volumes:
      - ./prisma:/app/prisma
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    profiles:
      - dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web






