version: '3.8'

services:
  web:
    build: .
    expose:
      - "4321"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/database.db
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production-and-use-a-strong-secret-key}
    volumes:
      - ./prisma:/app/prisma
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web 